//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseCommunicator.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        public Action()
        {
            this.CalendarEventExecutedActions = new HashSet<CalendarEventExecutedAction>();
            this.CalendarEvents = new HashSet<CalendarEvent>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string LongName { get; set; }
        public string Material { get; set; }
        public int RecommendedLength { get; set; }
        public decimal Costs { get; set; }
        public decimal Margin { get; set; }
        public Nullable<decimal> InsuranceCompanyMargin { get; set; }
        public Nullable<int> InsuranceCompanyID { get; set; }
        public Nullable<int> EzkoFieldID { get; set; }
        public bool HasSpecification { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual InsuranceCompany InsuranceCompany { get; set; }
        public virtual Field Field { get; set; }
        public virtual ICollection<CalendarEventExecutedAction> CalendarEventExecutedActions { get; set; }
        public virtual ICollection<CalendarEvent> CalendarEvents { get; set; }
    }
}
