//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseCommunicator.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget
    {
        public Budget()
        {
            this.BudgetItems = new HashSet<BudgetItem>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int PatientID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual ICollection<BudgetItem> BudgetItems { get; set; }
    }
}
