//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseCommunicator.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetItem
    {
        public int ID { get; set; }
        public int Count { get; set; }
        public decimal UnitPrice { get; set; }
        public int BudgetID { get; set; }
    
        public virtual Budget Budget { get; set; }
    }
}
