//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseCommunicator.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarEventColor
    {
        public CalendarEventColor()
        {
            this.CalendarEvents = new HashSet<CalendarEvent>();
        }
    
        public int ID { get; set; }
        public int R { get; set; }
        public int G { get; set; }
        public int B { get; set; }
    
        public virtual ICollection<CalendarEvent> CalendarEvents { get; set; }
    }
}
