//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseCommunicator.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventState
    {
        public EventState()
        {
            this.CalendarEvents = new HashSet<CalendarEvent>();
            this.CalendarEventColors = new HashSet<CalendarEventColor>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<CalendarEvent> CalendarEvents { get; set; }
        public virtual ICollection<CalendarEventColor> CalendarEventColors { get; set; }
    }
}
