//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseCommunicator.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExecutedActionNote
    {
        public ExecutedActionNote()
        {
            this.CalendarEventExecutedActions = new HashSet<CalendarEventExecutedAction>();
        }
    
        public int ID { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<CalendarEventExecutedAction> CalendarEventExecutedActions { get; set; }
    }
}
