//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseCommunicator.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Field
    {
        public Field()
        {
            this.Actions = new HashSet<Action>();
            this.FieldForms = new HashSet<FieldForm>();
            this.FieldValues = new HashSet<FieldValue>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string StandardNumber { get; set; }
        public string OtherName { get; set; }
        public string Description { get; set; }
        public int TypeID { get; set; }
        public int SectionID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<Action> Actions { get; set; }
        public virtual FieldType FieldType { get; set; }
        public virtual Section Section { get; set; }
        public virtual ICollection<FieldForm> FieldForms { get; set; }
        public virtual ICollection<FieldValue> FieldValues { get; set; }
    }
}
