//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseCommunicator.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldValue
    {
        public int ID { get; set; }
        public int FieldID { get; set; }
        public string Value { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Field Field { get; set; }
    }
}
