//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseCommunicator.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldForm
    {
        public int FieldID { get; set; }
        public int FormID { get; set; }
        public int QuestionID { get; set; }
    
        public virtual Field Field { get; set; }
        public virtual Form Form { get; set; }
        public virtual Question Question { get; set; }
    }
}
