//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseCommunicator.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilledField
    {
        public FilledField()
        {
            this.FieldValueAnswers = new HashSet<FieldValueAnswer>();
        }
    
        public int ID { get; set; }
        public int FieldID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> FieldAnswerID { get; set; }
    
        public virtual Field Field { get; set; }
        public virtual FieldAnswer FieldAnswer { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<FieldValueAnswer> FieldValueAnswers { get; set; }
    }
}
