//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseCommunicator.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Infrastructure
    {
        public Infrastructure()
        {
            this.CalendarEvents = new HashSet<CalendarEvent>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Costs { get; set; }
        public decimal Margin { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<CalendarEvent> CalendarEvents { get; set; }
    }
}
