//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseCommunicator.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceCompany
    {
        public InsuranceCompany()
        {
            this.Actions = new HashSet<Action>();
            this.Patients = new HashSet<Patient>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<Action> Actions { get; set; }
        public virtual ICollection<Patient> Patients { get; set; }
    }
}
