//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseCommunicator.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.FieldForms = new HashSet<FieldForm>();
        }
    
        public int ID { get; set; }
        public string Value { get; set; }
        public Nullable<int> Index { get; set; }
    
        public virtual ICollection<FieldForm> FieldForms { get; set; }
    }
}
