//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseCommunicator.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.CalendarEvents = new HashSet<CalendarEvent>();
        }
    
        public int ID { get; set; }
        public string Login { get; set; }
        public string Email { get; set; }
        public int RoleID { get; set; }
        public string Password { get; set; }
        public string RootDirectoryPath { get; set; }
        public bool IsDeleted { get; set; }
        public string AvatarImagePath { get; set; }
    
        public virtual UserRole UserRole { get; set; }
        public virtual ICollection<CalendarEvent> CalendarEvents { get; set; }
    }
}
