//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZKO.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EZKO.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string ActionOutput {
            get {
                return ResourceManager.GetString("ActionOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        internal static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambulantion.
        /// </summary>
        internal static string Ambulantion {
            get {
                return ResourceManager.GetString("Ambulantion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered user name or password are wrong.
        /// </summary>
        internal static string BadLoginData {
            get {
                return ResourceManager.GetString("BadLoginData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create visit.
        /// </summary>
        internal static string CreateEvent {
            get {
                return ResourceManager.GetString("CreateEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteEvent {
            get {
                return ResourceManager.GetString("DeleteEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be divisible by 5.
        /// </summary>
        internal static string DivisibleBy5Error {
            get {
                return ResourceManager.GetString("DivisibleBy5Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        internal static string Doctor {
            get {
                return ResourceManager.GetString("Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done actions.
        /// </summary>
        internal static string DoneActions {
            get {
                return ResourceManager.GetString("DoneActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done actions text.
        /// </summary>
        internal static string DoneActionsText {
            get {
                return ResourceManager.GetString("DoneActionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose....
        /// </summary>
        internal static string EditUserForm_ChooseImage {
            get {
                return ResourceManager.GetString("EditUserForm_ChooseImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string EditUserForm_ConfirmPassword {
            get {
                return ResourceManager.GetString("EditUserForm_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Create user.
        /// </summary>
        internal static string EditUserForm_CreateUser {
            get {
                return ResourceManager.GetString("EditUserForm_CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        internal static string EditUserForm_EditUser {
            get {
                return ResourceManager.GetString("EditUserForm_EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show password.
        /// </summary>
        internal static string EditUserForm_ShowPassword {
            get {
                return ResourceManager.GetString("EditUserForm_ShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit users.
        /// </summary>
        internal static string EditUserForm_Title {
            get {
                return ResourceManager.GetString("EditUserForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name (1-25 characters).
        /// </summary>
        internal static string EditUserForm_UserName {
            get {
                return ResourceManager.GetString("EditUserForm_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string EditUserForm_UserRole {
            get {
                return ResourceManager.GetString("EditUserForm_UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string EventState {
            get {
                return ResourceManager.GetString("EventState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick setup.
        /// </summary>
        internal static string FastSettings {
            get {
                return ResourceManager.GetString("FastSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account was deactivated.
        /// </summary>
        internal static string InactiveUser {
            get {
                return ResourceManager.GetString("InactiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading dashboard panel....
        /// </summary>
        internal static string LoadingDashboardPanel {
            get {
                return ResourceManager.GetString("LoadingDashboardPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading the data.
        /// </summary>
        internal static string LoadingDataTitle {
            get {
                return ResourceManager.GetString("LoadingDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while trying to login user into the system.
        /// </summary>
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        internal static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New patient.
        /// </summary>
        internal static string NewPatient {
            get {
                return ResourceManager.GetString("NewPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New visit.
        /// </summary>
        internal static string NewVisit {
            get {
                return ResourceManager.GetString("NewVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification emails (separate by comma).
        /// </summary>
        internal static string NotificationEmails {
            get {
                return ResourceManager.GetString("NotificationEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nurse.
        /// </summary>
        internal static string Nurse {
            get {
                return ResourceManager.GetString("Nurse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        internal static string Patient {
            get {
                return ResourceManager.GetString("Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients.
        /// </summary>
        internal static string Patients {
            get {
                return ResourceManager.GetString("Patients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal schedule of doctor.
        /// </summary>
        internal static string PersonalSchedule {
            get {
                return ResourceManager.GetString("PersonalSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned actions.
        /// </summary>
        internal static string PlannedActions {
            get {
                return ResourceManager.GetString("PlannedActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned text.
        /// </summary>
        internal static string PlannedText {
            get {
                return ResourceManager.GetString("PlannedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing EZKO.
        /// </summary>
        internal static string PreparingSystem {
            get {
                return ResourceManager.GetString("PreparingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order again.
        /// </summary>
        internal static string ReorderEvent {
            get {
                return ResourceManager.GetString("ReorderEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveEvent {
            get {
                return ResourceManager.GetString("SaveEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The beggining.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add and edit user accounts.
        /// </summary>
        internal static string UsersTooltip {
            get {
                return ResourceManager.GetString("UsersTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit note.
        /// </summary>
        internal static string VisitNote {
            get {
                return ResourceManager.GetString("VisitNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working....
        /// </summary>
        internal static string Working {
            get {
                return ResourceManager.GetString("Working", resourceCulture);
            }
        }
    }
}
